---
- hosts: localhost
  gather_facts: false
  become: false
  vars:
    # Defines the openstack-ansible release to use
    osa_release: "stable/rocky"
    # Defines if environment should be provisioned as an openstack-ansible all-in-one
    osa_aio: false
    # Defines if Ceph is to be used
    osa_ceph: false
    # Defines if cells should be created
    osa_cells: false
    # Defines the number of controllers to spin up
    osa_controllers:
      count: 1
      cpu: 4
      memory: 16384
    # Defines the number of compute nodes to spin up
    osa_compute:
      count: 2
      cpu: 4
      memory: 8192
    # Defines the number of Ceph nodes to spin up
    osa_ceph:
      count: 3
      cpu: 1
      memory: 4096
    # Defines the numer of openstack-ansible all-in-ones to spin up
    osa_aio:
      count: 0
      cpu: 4
      memory: 16384
    # Defines the dns domain name for environment
    osa_domain: test.vagrant.local
    # Defines the netmask cidr for environment
    osa_ip_netmask: 22
    # Defines the subnets for environment
    osa_ip_subnet: 192.168.200.0
    osa_mgmt_subnet: 172.29.236.0
    osa_flat_subnet: 192.168.100.0
    osa_vlan_subnet: 10.10.0.0
    osa_vxlan_subnet: 172.26.240.0
    osa_storage_subnet: 172.29.244.0
    # Defines the primary interface of VMs to use
    osa_pri_interface: enp0s8
    # Defines the VIP of environment
    osa_vip: 192.168.200.100
    # Defines the Vagrant box image to use
    vagrant_image: bunchc/bionic64
    # Defines the provider to use
    vagrant_provider: libvirt
  tasks:
    # Generates an updated nodes.yml for Vagrant
    - name: Generating Nodes
      template:
        src: templates/nodes.yml.j2
        dest: ./nodes.yml

    # Generates an updated group_vars/all/all.yml
    - name: Generating group_vars/all/all.yml
      template:
        src: templates/group_vars/all/all.yml.j2
        dest: ./group_vars/all/all.yml
        backup: true