---
- hosts: elkstack
  become: true
  become_method: sudo
  roles:
    - role: ansible-change-hostname
    - role: ansible-apt-cacher-ng
    - role: ansible-etc-hosts
    - role: ansible-ntp
    - role: ansible-timezone

- hosts: openstack
  become: true
  become_method: sudo
  roles:
    - role: ansible-osa-aio
