---
- hosts: elkstack
  become: true
  become_method: sudo
  roles:
    - role: ansible-change-hostname
    - role: ansible-apt-cacher-ng
    - role: ansible-etc-hosts
    - role: ansible-ntp
    - role: ansible-timezone
    - role: ansible-rsyslog
    - role: ansible-telegraf

- hosts: brokers
  roles:
    - role: ansible-rabbitmq
      when: brokers_use_rabbitmq
    - role: ansible-redis
      when: brokers_use_redis

- hosts: pre_processors
  roles:
    - role: ansible-dnsmasq
    - role: ansible-logstash
    - role: ansible-elk-pre-processor

- hosts: processors
  roles:
    - role: ansible-dnsmasq
    - role: ansible-logstash
    - role: ansible-elk-processor

- hosts: elasticsearch
  roles:
    - role: ansible-elasticsearch

- hosts: loadbalancers
  become: true
  become_method: sudo
  roles:
    - role: ansible-keepalived
    - role: ansible-haproxy

- hosts: dashboard
  roles:
    - role: ansible-grafana
    - role: ansible-kibana

- hosts: influx
  roles:
    - role: ansible-influxdb

- hosts: influx_relay
  roles:
    - role: ansible-influxdb-relay

- hosts: openstack
  become: true
  become_method: sudo
  roles:
    - role: ansible-monitorstack
    - role: ansible-osa-aio
#  tasks:
#    - name: Clone openstack-ansible
#      git:
#        repo: https://github.com/openstack/openstack-ansible
#        dest: /opt/openstack-ansible
#        version: "{{ release }}"
#    - name: Bootstrap Ansible
#      shell: scripts/bootstrap-ansible.sh
#      args:
#        chdir: /opt/openstack-ansible
#    - name: Bootstrap AIO
#      shell: scripts/bootstrap-aio.sh
#      args:
#        chdir: /opt/openstack-ansible
#    - name: Running setup-hosts.yml
#      shell: openstack-ansible setup-hosts.yml
#      args:
#        chdir: /opt/openstack-ansible/playbooks
#    - name: Running setup-infrastructure.yml
#      shell: openstack-ansible setup-infrastructure.yml
#      args:
#        chdir: /opt/openstack-ansible/playbooks
#    - name: Running setup-openstack.yml
#      shell: openstack-ansible setup-openstack.yml
#      args:
#        chdir: /opt/openstack-ansible/playbooks
