---
# Creates a service specific config file for every service defined
# Borrowed from openstack-ansible-haproxy_server
# https://github.com/openstack/openstack-ansible-haproxy_server/blob/master/tasks/haproxy_service_config.yml

- name: "Create haproxy service config files"
  template:
    src: etc/haproxy/service.cfg.j2
    dest: "/etc/haproxy/conf.d/{{ item.service.haproxy_service_name }}"
  with_items: "{{ haproxy_service_configs | default([]) }}"
  when:
    - (item.service.haproxy_backend_nodes is defined and
      item.service.haproxy_backend_nodes | length > 0) or
      (item.service.haproxy_backup_nodes is defined and
      item.service.haproxy_backup_nodes | length > 0)
    - item.service.haproxy_service_enabled | default('True') | bool
  notify: Regenerate haproxy configuration