---

- name: instances | Creating keypair
  os_keypair:
    verify: no
    cloud: default
    state: present
    name: "{{ item['name'] }}"
  with_items: "{{  osa_keypairs }}"
  delegate_to: localhost

- name: instances | Creating flavors
  os_nova_flavor:
    cloud: default
    state: present
    name: "{{ item['name'] }}"
    ram: "{{ item['ram'] }}"
    vcpus: "{{ item['vcpus'] }}"
    disk: "{{ item['disk'] }}"
  with_items: "{{ osa_nova_flavors }}"
  delegate_to: localhost

- name: instances | Launching instances
  os_server:
    cloud: default
    name: "{{ item['name'] }}"
    image: "{{ item['image'] }}"
    key_name: "{{ item['key_name'] }}"
    timeout: "{{ item['timeout'] }}"
    flavor: "{{ item['flavor'] }}"
    network: "{{ item['network'] }}"
    security_groups: "{{ item['security_groups'] }}"
    verify: false
    state: present
  with_items: "{{ osa_instances }}"
  delegate_to: localhost

