---
# Configures nova cells
- name: cells | Copy cells playbooks into place
  template:
    src: "{{ item }}.j2"
    dest: "{{ osa_download_location }}/playbooks/{{ item }}"
  with_items:
    - "osa-cells-create_db.yml"
    - "osa-cells-create_mq.yml"

- name: cells | Create databases
  shell: openstack-ansible osa-cells-create_db.yml
  args:
    chdir: "{{ osa_download_location }}/playbooks"
  register: cells_db

- name: cells | Create message queues
  shell: openstack-ansible osa-cells-create_mq.yml
  args:
    chdir: "{{ osa_download_location }}/playbooks"
  when: >
          cells_db is defined and
          cells_db.rc == 0
