galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible](https://www.ansible.com) role to install/configure [Elasticsearch](https://www.elastic.co/products/elasticsearch)

  license: license (MIT)

  min_ansible_version: 1.2

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - 22
        - 23
    - name: Ubuntu
      versions:
        - trusty
        - vivid
        - wily
        - xenial
  galaxy_tags:
    - database
    - database:nosql

dependencies: []
