---
keepalived_config: true
keepalived_router_info:
  - name: vrrp_1
    check_script:
      - name: chk_haproxy
        script: 'killall -0 haproxy'
        interval: 2
        weight: 2
    # Define inventory_hostname of node to be considered Master
    master_node: "{{ groups['loadbalancers'][0] }}"
    router_id: 50
    router_pri_backup: 100
    router_pri_master: 150
    vip_int: "{{ hostvars[inventory_hostname]['ansible_'+pri_interface]['device'] }}"
    vip_addresses:
      - "{{ vip }}"
